### ISSUE TITLE
How do you handle sequences longer than 1022 with esm1b?

### ISSUE THREAD

**Issue by YuanshengH** [AlexanderKroll/kcat_prediction#3]
There are numerous amino acid sequences in the training and testing sets that exceed a length of 1022. However, the input length for esm1b is capped at 1022.  How do you handle sequences longer than 1022 with esm1b?

**Comment by AlexanderKroll** [comment]
You are completely right that ESM-1b cannot process sequences longer than 1024 (or subtracting the extra tokens tokens: 1022). As specified in our paper, in this case we only use the first 1022 amino acids as an input for the ESM-1b model.
