### ISSUE TITLE
model_ESM_binary_A100_epoch_1_new_split.pkl  not found

### ISSUE THREAD

**Issue by fazhang-master** [AlexanderKroll/kcat_prediction#4]
Step 1/3: Calculating numerical representations for all substrates and products.
Step 2/3: Calculating numerical representations for all enzymes.
.....2(a) Loading ESM-1b model.
.....2(b) Loading model parameters for task-specific model.
Traceback (most recent call last):
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\pyqt1.0.py", line 78, in <module>
    enzymes = enzymes)
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\kcat_prediction.py", line 26, in kcat_predicton
    df_enzyme = calcualte_esm1b_ts_vectors(enzyme_list = enzymes)
  File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\enzyme_representations.py", line 45, in calcualte_esm1b_ts_vectors
    model_dict = torch.load(PATH, map_location=torch.device('cpu'))
  File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\desktop\\demo\\Kcat生物信息\\kcat_prediction_function\\kcat_prediction_function-main\\code\\data\\saved_models\\ESM1b\\model_ESM_binary_A100_epoch_1_new_split.pkl'

**Comment by whitene** [comment]
> Step 1/3: Calculating numerical representations for all substrates and products. Step 2/3: Calculating numerical representations for all enzymes. .....2(a) Loading ESM-1b model. .....2(b) Loading model parameters for task-specific model. Traceback (most recent call last): File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\pyqt1.0.py", line 78, in enzymes = enzymes) File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\kcat_prediction.py", line 26, in kcat_predicton df_enzyme = calcualte_esm1b_ts_vectors(enzyme_list = enzymes) File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\enzyme_representations.py", line 45, in calcualte_esm1b_ts_vectors model_dict = torch.load(PATH, map_location=torch.device('cpu')) File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 771, in load with _open_file_like(f, 'rb') as opened_file: File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 270, in _open_file_like return _open_file(name_or_buffer, mode) File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 251, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\data\saved_models\ESM1b\model_ESM_binary_A100_epoch_1_new_split.pkl'

Have you solved this problem?Could you tell me how to solve it?

**Comment by whitene** [comment]
> Step 1/3: Calculating numerical representations for all substrates and products. Step 2/3: Calculating numerical representations for all enzymes. .....2(a) Loading ESM-1b model. .....2(b) Loading model parameters for task-specific model. Traceback (most recent call last): File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\pyqt1.0.py", line 78, in enzymes = enzymes) File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\kcat_prediction.py", line 26, in kcat_predicton df_enzyme = calcualte_esm1b_ts_vectors(enzyme_list = enzymes) File "F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\enzyme_representations.py", line 45, in calcualte_esm1b_ts_vectors model_dict = torch.load(PATH, map_location=torch.device('cpu')) File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 771, in load with _open_file_like(f, 'rb') as opened_file: File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 270, in _open_file_like return _open_file(name_or_buffer, mode) File "I:\conda\envs\KM\lib\site-packages\torch\serialization.py", line 251, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'F:\desktop\demo\Kcat生物信息\kcat_prediction_function\kcat_prediction_function-main\code\data\saved_models\ESM1b\model_ESM_binary_A100_epoch_1_new_split.pkl'

你好，请问能收到我的消息吗？我运行这个软件也出现了相同的问题，请问你是怎么解决的啊，可以告诉我吗？
